### ISSUE TITLE
EventSource / Server-Sent Events

### ISSUE THREAD

**Issue by nghamilton** [collegevine/firebase#5]
Hi - do you have any plans for integration of SSEs into the project to support listening to data changes? (As per REST API in https://firebase.google.com/docs/reference/rest/database/). Or do you know of any other implementations that do? If not, I might work up something and then submit a pull request. (Thanks for the library, by the way).

**Comment by mohanzhang** [comment]
@nghamilton We do not currently have any plans to further develop this library. We gave firebase a fair shot for a year, but we left wholly unimpressed and have removed it from our tech stack altogether. It just wasn't a good fit for us, unfortunately.

**Comment by nghamilton** [comment]
Ok, thanks. What was the major issue/s you had with using Firebase, if you
don't mind me asking? A year seems a very fair trial to fully understand
the drawbacks.

**Comment by chshersh** [comment]
@mohanzhang I'm also interested in issues with using Firebase. And what do you use now? Would be nice to hear better alternatives!
